version: '3.7'

# referencia: https://www.digitalocean.com/community/users/katjuell

services:

  wp_mysql:
    image: mysql:8.0.21
    container_name: alx-mysql
    platform: linux/x86_64
    volumes:
      - ./mysql/db_data:/var/lib/mysql
      - ./mysql/local.sql:/docker-entrypoint-initdb.d/local.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: alxwp
      MYSQL_ROOT_PASSWORD: ksdfklwqjdfal22k4s
      MYSQL_USER: alxwp
      MYSQL_PASSWORD: ksdfklwqjdfal22k4s
    ports:
      - "3306:3306"
    networks:
      - alxnetwp

  wordpress:
    depends_on:
      - wp_mysql
    build: .
    container_name: alx-wp
    restart: always
    volumes: 
      - ./wordpress:/var/www/html
    networks:
      - alxnetwp
    links:
      - wp_mysql

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: alx-webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      # - ./certbot-etc:/etc/letsencrypt
    networks:
      - alxnetwp
    links:
      - wordpress

  # certbot:
  #   depends_on:
  #     - alx-webserver
  #   image: certbot/certbot
  #   container_name: alx-certbot
  #   volumes:
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./wordpress:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email alexlana@gmail.com --agree-tos --no-eff-email --staging -d localhost -d localhost.com

volumes:
  db_data:

networks:
  alxnetwp:



